package top.ltfan.dslutilities.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets

/**
 * Processes interfaces annotated with
 * [DslBuilder][top.ltfan.dslutilities.DslBuilder] and generates a
 * builder class, an immutable result data class, and a top-level
 * build function for each of them. Child scopes declared with
 * [DslChild][top.ltfan.dslutilities.DslChild] and list children declared
 * through [DslList][top.ltfan.dslutilities.DslList] receive generated
 * composition functions.
 */
class DslProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val deferred = mutableListOf<KSAnnotated>()
        resolver
            .getSymbolsWithAnnotation("top.ltfan.dslutilities.DslBuilder")
            .filterIsInstance<KSClassDeclaration>()
            .forEach { spec ->
                // Specs that reference types generated by later processor
                // rounds come back unresolved; deferring them lets KSP retry
                // in the next round instead of failing the build.
                if (!generate(spec)) deferred += spec
            }
        return deferred
    }

    /**
     * Generates the code for one spec. Returns `false` when the spec should be
     * deferred to a later round because it only references unresolvable types;
     * diagnostics for genuine errors are reported before returning `true`.
     */
    private fun generate(spec: KSClassDeclaration): Boolean {
        val specName = spec.simpleName.asString()
        val packageName = spec.packageName.asString()
        val annotation = spec.annotation(DSL_BUILDER_ANNOTATION)
        val names = Names.of(specName, annotation)

        if (spec.classKind != ClassKind.INTERFACE) {
            logger.error("@DslBuilder applies to interfaces, but $specName is a ${spec.classKind}.", spec)
            return true
        }
        if (names.resultName == specName || names.builderName == specName) {
            logger.error("The result and builder names of $specName must differ from the interface name.", spec)
            return true
        }
        if (names.resultName == names.builderName) {
            logger.error("The result and builder names of $specName must differ from each other.", spec)
            return true
        }
        if (!names.generateFunction && names.functionName.isNotEmpty()) {
            logger.error("@DslBuilder.functionName of $specName requires generateFunction.", spec)
            return true
        }

        val checker = Checker(logger)
        val requiredProperties = mutableListOf<RequiredProperty>()
        val valueProperties = mutableListOf<ValueProperty>()
        val listProperties = mutableListOf<ListProperty>()
        val childScopes = mutableListOf<ChildScope>()
        val supertype = annotation
            ?.type("supertype")
            ?.takeIf { it.declaration.qualifiedName?.asString() != "kotlin.Unit" }
            ?.let { checker.renderType(spec, it) }
        if (!checker.valid) return handled(checker)

        for (property in spec.declarations.filterIsInstance<KSPropertyDeclaration>()) {
            val name = property.simpleName.asString()
            val type = property.type.resolve()
            val dslValue = property.annotation(DSL_VALUE_ANNOTATION)
            val dslList = property.annotation(DSL_LIST_ANNOTATION)

            if (dslList != null) {
                listProperty(name, property, type, dslList, checker)?.let(listProperties::add)
            } else if (!property.isMutable) {
                requiredProperty(name, property, type, dslValue, checker)?.let(requiredProperties::add)
            } else if (dslValue != null) {
                valueProperty(name, property, type, dslValue, checker)?.let(valueProperties::add)
            } else {
                checker.report(property, "Property $name must be annotated with @DslValue or @DslList.")
            }
        }

        for (function in spec.declarations.filterIsInstance<KSFunctionDeclaration>()) {
            val name = function.simpleName.asString()
            if (function.annotation(DSL_CHILD_ANNOTATION) == null) {
                checker.report(
                    function,
                    "Function $name must be annotated with @DslChild; DslBuilder interfaces declare properties and @DslChild functions."
                )
                continue
            }
            childScope(name, function, checker)?.let(childScopes::add)
        }

        if (!checker.valid) return handled(checker)

        val code = buildString {
            appendLine("// Generated by dsl-utilities-ksp from ${spec.qualifiedName?.asString() ?: specName}. Do not edit.")
            if (packageName.isNotEmpty()) {
                appendLine("package $packageName")
                appendLine()
            }

            append("public class ${names.builderName}(")
            requiredProperties.joinTo(this, ", ") { "public override val ${it.name}: ${it.typeName}" }
            appendLine(") : $specName {")

            for (property in valueProperties) {
                appendLine("    private var ${property.name}Field: ${property.storageTypeName} = ${property.initialExpression}")
            }
            for (property in listProperties) {
                appendLine("    private val ${property.name}Field: MutableList<${property.elementTypeName}> = mutableListOf()")
            }
            for (property in childScopes) {
                appendLine("    private var ${property.name}Field: ${property.child.resultQualifiedName}? = null")
            }
            if (valueProperties.isNotEmpty() || listProperties.isNotEmpty() || childScopes.isNotEmpty()) appendLine()

            for (property in valueProperties) {
                appendLine("    override var ${property.name}: ${property.typeName}")
                appendLine("        get() = ${property.getterExpression("${property.name}Field")}")
                appendLine("        set(value) {")
                if (property.mapper == null) {
                    if (property.validator != null) {
                        appendLine(
                            "            require(${property.validator}.validate(value)) { \"${
                                escapeStringLiteral(
                                    property.message
                                )
                            }\" }"
                        )
                    }
                    appendLine("            ${property.name}Field = value")
                } else {
                    appendLine("            val stored = ${property.mapper}.toStored(value)")
                    if (property.validator != null) {
                        appendLine(
                            "            require(${property.validator}.validate(stored)) { \"${
                                escapeStringLiteral(
                                    property.message
                                )
                            }\" }"
                        )
                    }
                    appendLine("            ${property.name}Field = stored")
                }
                appendLine("        }")
                appendLine()
            }

            for (property in valueProperties) {
                val validateDefault = property.initialExpression != "null" || property.validatorAcceptsNull
                if (property.validator != null && validateDefault) {
                    appendLine("    init {")
                    appendLine(
                        "        require(${property.validator}.validate(${property.name}Field)) { \"${
                            escapeStringLiteral(property.message)
                        }\" }"
                    )
                    appendLine("    }")
                    appendLine()
                }
            }

            for (property in listProperties) {
                appendLine("    override var ${property.name}: MutableList<${property.elementTypeName}>")
                appendLine("        get() = ${property.name}Field")
                appendLine("        set(value) {")
                appendLine("            val snapshot = value.toList()")
                appendLine("            ${property.name}Field.clear()")
                appendLine("            ${property.name}Field.addAll(snapshot)")
                appendLine("        }")
                appendLine()
            }

            for (property in childScopes) {
                append("    override fun ${property.name}(")
                val parameters = property.parameters.map { "${it.name}: ${it.typeName}" } +
                        "block: ${property.child.specQualifiedName}.() -> Unit"
                append(parameters.joinToString(", "))
                appendLine(") {")
                append("        ${property.name}Field = ${property.child.builderQualifiedName}(")
                append(property.child.required.joinToString(", ") { "${it.name} = ${it.name}" })
                appendLine(").apply(block).build()")
                appendLine("    }")
                appendLine()
            }

            appendLine("    public fun build(): ${names.resultName} {")
            for (property in requiredProperties) {
                if (property.validator != null) {
                    appendLine(
                        "        require(${property.validator}.validate(${property.name})) { \"${
                            escapeStringLiteral(
                                property.message
                            )
                        }\" }"
                    )
                }
            }
            for (property in listProperties) {
                if (property.validator != null) {
                    appendLine("        for (element in ${property.name}Field) {")
                    appendLine(
                        "            require(${property.validator}.validate(element)) { \"${
                            escapeStringLiteral(
                                property.message
                            )
                        }\" }"
                    )
                    appendLine("        }")
                }
            }
            appendLine("        return ${names.resultName}(")
            for (property in requiredProperties) {
                appendLine("            ${property.name} = ${property.name},")
            }
            for (property in valueProperties) {
                appendLine("            ${property.name} = ${property.name},")
            }
            for (property in listProperties) {
                appendLine("            ${property.name} = ${property.name}Field.toList(),")
            }
            for (property in childScopes) {
                appendLine("            ${property.name} = requireNotNull(${property.name}Field) { \"Property ${property.name} is required.\" },")
            }
            appendLine("        )")
            appendLine("    }")
            appendLine("}")
            appendLine()

            for (property in listProperties) {
                for (child in property.children) {
                    append("public inline fun $specName.${child.functionName}(")
                    val parameters = child.required.map { "${it.name}: ${it.typeName}" } +
                            "block: ${child.specQualifiedName}.() -> Unit = {}"
                    append(parameters.joinToString(", "))
                    appendLine(") {")
                    append("    ${property.name}.add(${child.builderQualifiedName}(")
                    append(child.required.joinToString(", ") { "${it.name} = ${it.name}" })
                    appendLine(").apply(block).build())")
                    appendLine("}")
                    if (child.required.isEmpty()) {
                        appendLine()
                        appendLine("public inline val $specName.${child.functionName}: Unit")
                        appendLine("    get() = ${child.functionName}()")
                    }
                    appendLine()
                }
            }

            val resultProperties = requiredProperties.map { "${it.name}: ${it.typeName}" } +
                    valueProperties.map { "${it.name}: ${it.typeName}" } +
                    listProperties.map { "${it.name}: List<${it.elementTypeName}>" } +
                    childScopes.map { "${it.name}: ${it.child.resultQualifiedName}" }
            val resultClassKeyword = if (resultProperties.isEmpty()) "class" else "data class"
            append("public $resultClassKeyword ${names.resultName}(")
            append(resultProperties.joinToString(", ") { "public val $it" })
            append(")")
            if (supertype != null) append(" : $supertype")
            appendLine()

            appendLine()
            if (names.generateFunction) {
                if (requiredProperties.isEmpty()) {
                    appendLine("public inline fun ${names.functionName}(block: $specName.() -> Unit = {}): ${names.resultName} {")
                    appendLine("    val builder = ${names.builderName}()")
                    appendLine("    builder.block()")
                    appendLine("    return builder.build()")
                    appendLine("}")
                } else {
                    appendLine("public inline fun ${names.functionName}(")
                    for (property in requiredProperties) {
                        appendLine("    ${property.name}: ${property.typeName},")
                    }
                    appendLine("    block: $specName.() -> Unit = {},")
                    appendLine("): ${names.resultName} {")
                    append("    val builder = ${names.builderName}(")
                    append(requiredProperties.joinToString(", ") { "${it.name} = ${it.name}" })
                    appendLine(")")
                    appendLine("    builder.block()")
                    appendLine("    return builder.build()")
                    appendLine("}")
                }
            }
        }

        val file = codeGenerator.createNewFile(
            Dependencies(aggregating = true, *spec.containingFile?.let { arrayOf(it) } ?: emptyArray()),
            packageName,
            names.builderName,
        )
        OutputStreamWriter(file, StandardCharsets.UTF_8).use { writer ->
            writer.write(code)
        }
        return true
    }

    /**
     * Reports buffered diagnostics and returns `true` when the spec was
     * handled in this round. A spec whose failures are all unresolved
     * types stays unreported so the caller can defer it to a later round.
     */
    private fun handled(checker: Checker): Boolean {
        if (checker.onlyUnresolved()) return false
        checker.flush()
        return true
    }

    /**
     * Required properties are declared as `val`: they are parameters of the
     * generated builder and of the generated build function, so the compiler
     * enforces their presence.
     */
    private fun requiredProperty(
        name: String,
        property: KSPropertyDeclaration,
        type: KSType,
        annotation: KSAnnotation?,
        checker: Checker,
    ): RequiredProperty? {
        val typeName = checker.renderTypeReference(property, property.type) ?: return null
        if (annotation?.string("initial")?.isNotEmpty() == true) {
            checker.report(property, "@DslValue.initial applies to var properties; $name is a val.")
            return null
        }
        val mapperType = annotation?.type("mapper")
        if (mapperType != null && mapperType.declaration.qualifiedName?.asString() != "kotlin.Unit") {
            checker.report(property, "@DslValue.mapper applies to var properties; $name is a val.")
            return null
        }
        val validator = checker.validator(property, name, annotation?.type("validator"), type)
        if (!checker.valid) return null
        return RequiredProperty(name, typeName, validator?.prefix, checker.message(annotation, name))
    }

    /**
     * Value properties are declared as `var` with
     * [DslValue][top.ltfan.dslutilities.DslValue]: they are set inside the
     * DSL block with the validator and mapper wired inline into the generated
     * accessors.
     */
    private fun valueProperty(
        name: String,
        property: KSPropertyDeclaration,
        type: KSType,
        annotation: KSAnnotation,
        checker: Checker,
    ): ValueProperty? {
        if (type.declaration.qualifiedName?.asString() == "kotlin.collections.MutableList") {
            checker.report(
                property,
                "Property $name has a MutableList type; list properties are declared with @DslList."
            )
            return null
        }
        val typeName = checker.renderTypeReference(property, property.type) ?: return null
        val mapper = checker.mapper(property, name, annotation.type("mapper"), type)
        if (!checker.valid) return null
        val initial = annotation.string("initial").orEmpty().takeIf { it.isNotEmpty() }
        when (initial) {
            null if !type.isMarkedNullable -> {
                checker.report(
                    property,
                    "Property $name is non-nullable and has no initial value; declare it as a val to make it required, declare it with a nullable type, or provide @DslValue.initial."
                )
                return null
            }

            null if mapper != null -> {
                checker.report(
                    property,
                    "Property $name is nullable and has a mapper; provide @DslValue.initial so the stored value is always present."
                )
                return null
            }
        }
        val initialExpression = if (initial == null) {
            "null"
        } else {
            val literal = checker.literal(property, name, initial, type) ?: return null
            if (mapper != null) "${mapper.prefix}.toStored($literal)" else literal
        }
        val validator = checker.validator(
            property,
            name,
            annotation.type("validator"),
            mapper?.storedType ?: type,
        )
        if (!checker.valid) return null
        return ValueProperty(
            name = name,
            typeName = typeName,
            storageTypeName = mapper?.storageTypeName ?: typeName,
            initialExpression = initialExpression,
            mapper = mapper?.prefix,
            validator = validator?.prefix,
            validatorAcceptsNull = validator?.acceptsNull == true,
            message = checker.message(annotation, name),
        )
    }

    /**
     * List properties are declared as `var` with
     * [DslList][top.ltfan.dslutilities.DslList]: their elements are mutated
     * inside the DSL block and are validated in the generated build function;
     * the generated result class exposes them as read-only lists. Each
     * declared child receives a generated element function that builds the
     * child value and adds it to the list.
     */
    private fun listProperty(
        name: String,
        property: KSPropertyDeclaration,
        type: KSType,
        annotation: KSAnnotation,
        checker: Checker,
    ): ListProperty? {
        if (!property.isMutable) {
            checker.report(property, "@DslList applies to var properties; $name is a val.")
            return null
        }
        if (type.declaration.qualifiedName?.asString() != "kotlin.collections.MutableList" || type.arguments.size != 1) {
            checker.report(
                property,
                "Property $name annotated with @DslList has a type other than MutableList of the element type."
            )
            return null
        }
        val elementType = type.arguments.single().type?.resolve() ?: run {
            checker.report(property, "Property $name has an unsupported element type.")
            return null
        }
        val elementTypeReference = type.arguments.single().type
        if (elementTypeReference == null) {
            checker.report(property, "Property $name has an unsupported element type.")
            return null
        }
        val elementTypeName = checker.renderTypeReference(property, elementTypeReference) ?: return null
        val validator = checker.validator(property, name, annotation.type("validator"), elementType)
        if (!checker.valid) return null
        val validatorPrefix = validator?.prefix

        val children = mutableListOf<ChildSpec>()
        for (argumentType in annotation.typeArray("children")) {
            if (argumentType.isError) {
                checker.reportUnresolved(property, "A child of @DslList property $name is not resolvable yet.")
                return null
            }
            val childDeclaration = argumentType.declaration as? KSClassDeclaration ?: run {
                checker.report(property, "The children of @DslList property $name must be DslBuilder interfaces.")
                return null
            }
            children += resolveChild(childDeclaration, checker) ?: return null
        }
        if (!checker.valid) return null
        val functionNames = children.map { it.functionName }
        if (functionNames.size != functionNames.toSet().size) {
            checker.report(property, "Two or more children of @DslList property $name produce the same function name.")
            return null
        }
        return ListProperty(name, elementTypeName, validatorPrefix, checker.message(annotation, name), children)
    }

    /**
     * Child scopes are declared as `@DslChild` functions whose last parameter
     * is a function type with the child DslBuilder interface as receiver and
     * whose other parameters carry the required properties of the child; the
     * processor generates the function body.
     */
    private fun childScope(
        name: String,
        function: KSFunctionDeclaration,
        checker: Checker,
    ): ChildScope? {
        if (!function.isAbstract) {
            checker.report(function, "@DslChild function $name declares a body; the processor generates the body.")
            return null
        }
        val parameters = function.parameters
        if (parameters.isEmpty()) {
            checker.report(
                function,
                "@DslChild function $name declares no parameters; the last parameter must be a function type with the child DslBuilder interface as receiver."
            )
            return null
        }
        val blockParameter = parameters.last()
        val blockType = blockParameter.type.resolve()
        if (blockType.declaration.qualifiedName?.asString() != "kotlin.Function1" || blockType.arguments.size != 2) {
            checker.report(
                function,
                "The last parameter of @DslChild function $name must be a function type with the child DslBuilder interface as receiver."
            )
            return null
        }
        val receiverType = blockType.arguments[0].type?.resolve() ?: run {
            checker.report(
                function,
                "The last parameter of @DslChild function $name must be a function type with the child DslBuilder interface as receiver."
            )
            return null
        }
        val childDeclaration = receiverType.declaration as? KSClassDeclaration ?: run {
            checker.report(function, "The receiver of @DslChild function $name must be a DslBuilder interface.")
            return null
        }
        val child = resolveChild(childDeclaration, checker) ?: return null
        val declaredParameters = parameters.dropLast(1)
        if (declaredParameters.size != child.required.size) {
            checker.report(
                function,
                "@DslChild function $name declares ${declaredParameters.size} value parameters for a child with ${child.required.size} required properties."
            )
            return null
        }
        val scopeParameters = mutableListOf<Parameter>()
        for ((parameter, required) in declaredParameters.zip(child.required)) {
            val parameterName = parameter.name?.asString() ?: run {
                checker.report(function, "A parameter of @DslChild function $name has no name.")
                return null
            }
            val parameterTypeName = checker.renderTypeReference(function, parameter.type) ?: return null
            if (parameterName != required.name || parameterTypeName != required.typeName) {
                checker.report(
                    function,
                    "Parameter $parameterName of @DslChild function $name does not match required property ${required.name} of type ${required.typeName} of the child."
                )
                return null
            }
            scopeParameters += Parameter(parameterName, parameterTypeName)
        }
        return ChildScope(name, scopeParameters, child)
    }

    /**
     * Resolves a DslBuilder interface referenced as a child scope or as a list
     * child. The builder and result classes of the child follow the naming
     * rules of generated top-level classes, so children resolve across module
     * boundaries as well.
     */
    private fun resolveChild(declaration: KSClassDeclaration, checker: Checker): ChildSpec? {
        val specName = declaration.simpleName.asString()
        if (declaration.annotation(DSL_BUILDER_ANNOTATION) == null) {
            checker.report(declaration, "$specName must be annotated with @DslBuilder to be used as a child.")
            return null
        }
        if (declaration.classKind != ClassKind.INTERFACE) {
            checker.report(
                declaration,
                "@DslBuilder applies to interfaces, but $specName is a ${declaration.classKind}."
            )
            return null
        }
        val specQualifiedName = declaration.qualifiedName?.asString() ?: run {
            checker.report(declaration, "Child $specName has no qualified name.")
            return null
        }
        val names = Names.of(specName, declaration.annotation(DSL_BUILDER_ANNOTATION))
        val packageName = declaration.packageName.asString()
        fun qualify(name: String): String = if (packageName.isEmpty()) name else "$packageName.$name"
        val required = mutableListOf<RequiredProperty>()
        for (property in declaration.declarations.filterIsInstance<KSPropertyDeclaration>()) {
            if (property.isMutable) continue
            val typeName = checker.renderTypeReference(property, property.type) ?: return null
            required += RequiredProperty(property.simpleName.asString(), typeName, null, "")
        }
        return ChildSpec(
            functionName = decapitalize(specName.removeSuffix("Dsl").takeIf { it.isNotEmpty() } ?: specName),
            builderQualifiedName = qualify(names.builderName),
            resultQualifiedName = qualify(names.resultName),
            specQualifiedName = specQualifiedName,
            required = required,
        )
    }

    /**
     * Collects compile-time diagnostics and renders KSP types for the
     * generated code. Diagnostics are buffered: the caller reports them at
     * the end of generation, or defers the spec to a later round when every
     * diagnostic was an unresolved type.
     */
    private class Checker(private val logger: KSPLogger) {
        var valid = true
            private set

        private val pending = mutableListOf<Pair<KSNode, String>>()
        private var unresolvedCount = 0

        fun report(symbol: KSNode, message: String) {
            valid = false
            pending += symbol to message
        }

        /**
         * Records a diagnostic caused by a type that is not resolvable in this
         * round, typically because another symbol processor generates it later.
         */
        fun reportUnresolved(symbol: KSNode, message: String) {
            valid = false
            unresolvedCount++
            pending += symbol to message
        }

        /**
         * Returns `true` when every collected diagnostic was an unresolved type,
         * so processing can be deferred to a later KSP round.
         */
        fun onlyUnresolved(): Boolean = pending.isNotEmpty() && pending.size == unresolvedCount

        fun flush() {
            for ((symbol, message) in pending) logger.error(message, symbol)
            pending.clear()
        }

        fun message(annotation: KSAnnotation?, propertyName: String): String =
            annotation?.string("message").takeUnless { it.isNullOrEmpty() }
                ?: "Invalid value for property $propertyName."

        /**
         * Renders a type reference. Function types are rendered from the reference
         * structure so that the receiver, parameter names, suspend modifier and
         * type annotations are preserved.
         */
        fun renderTypeReference(symbol: KSNode, reference: KSTypeReference): String? {
            val element = reference.element
            if (element is KSCallableReference) {
                val resolved = reference.resolve()
                if (resolved.isError) {
                    reportUnresolved(symbol, "The type of ${symbolDescription(symbol)} is not resolvable yet.")
                    return null
                }
                val receiver = element.receiverType?.let { renderTypeReference(symbol, it) }
                val parameters = element.functionParameters.map { parameter ->
                    val typeName = renderTypeReference(symbol, parameter.type) ?: return null
                    val name = parameterName(parameter)
                    if (name == null) typeName else "$name: $typeName"
                }
                val returnType = renderTypeReference(symbol, element.returnType) ?: return null
                val annotations = (reference.annotations + resolved.annotations).toList()
                return formatFunctionType(
                    annotations = annotations,
                    isSuspend = resolved.isSuspendFunctionType,
                    receiver = receiver,
                    parameters = parameters,
                    returnType = returnType,
                    nullable = resolved.isMarkedNullable,
                )
            }
            return renderType(symbol, reference.resolve())
        }

        fun renderType(symbol: KSNode, type: KSType): String? {
            if (type.isFunctionType || type.isSuspendFunctionType) {
                val arguments = type.arguments.map { it.type }
                val isExtension = type.annotations.any { it.shortName.asString() == EXTENSION_FUNCTION_TYPE }
                val receiver = if (isExtension) {
                    arguments.firstOrNull()?.let { renderTypeReference(symbol, it) }
                } else {
                    null
                }
                val valueArguments = if (isExtension) arguments.drop(1) else arguments
                val parameters = valueArguments.dropLast(1).mapNotNull { argument ->
                    argument?.let { renderTypeReference(symbol, it) }
                }
                val returnType = valueArguments.lastOrNull()?.let { renderTypeReference(symbol, it) }
                    ?: UNIT_TYPE
                return formatFunctionType(
                    annotations = type.annotations.toList(),
                    isSuspend = type.isSuspendFunctionType,
                    receiver = receiver,
                    parameters = parameters,
                    returnType = returnType,
                    nullable = type.isMarkedNullable,
                )
            }
            val declaration = type.declaration
            val qualifiedName = declaration.qualifiedName?.asString()
            if (qualifiedName == null) {
                if (type.isError) {
                    reportUnresolved(symbol, "The type of ${symbolDescription(symbol)} is not resolvable yet.")
                } else {
                    report(symbol, "The type of ${symbolDescription(symbol)} is unsupported.")
                }
                return null
            }
            val arguments = if (type.arguments.isEmpty()) {
                ""
            } else {
                val rendered = type.arguments.map { argument ->
                    val argumentType = argument.type
                    if (argumentType == null) {
                        report(symbol, "A type argument of ${symbolDescription(symbol)} is unsupported.")
                        return null
                    }
                    renderTypeReference(symbol, argumentType) ?: return null
                }
                rendered.joinToString(", ", "<", ">")
            }
            return renderAnnotations(type.annotations) + qualifiedName + arguments +
                    if (type.isMarkedNullable) "?" else ""
        }

        /**
         * Resolves the name of a function type parameter. Kotlin stores the
         * declared name as a `@ParameterName` type annotation, so the value from
         * [KSValueParameter.name] is the placeholder `_` for function types.
         */
        private fun parameterName(parameter: KSValueParameter): String? {
            val name = parameter.name?.asString()
            if (name != null && name != "_") return name
            return parameter.type.annotations
                .firstOrNull { it.shortName.asString() == PARAMETER_NAME }
                ?.arguments
                ?.firstOrNull()
                ?.value as? String
        }

        private fun formatFunctionType(
            annotations: List<KSAnnotation>,
            isSuspend: Boolean,
            receiver: String?,
            parameters: List<String>,
            returnType: String,
            nullable: Boolean,
        ): String {
            val core = buildString {
                append(renderAnnotations(annotations.asSequence()))
                if (isSuspend) append("suspend ")
                if (receiver != null) append(receiver).append('.')
                append(parameters.joinToString(", ", "(", ")"))
                append(" -> ").append(returnType)
            }
            return if (nullable) "($core)?" else core
        }

        private fun renderAnnotations(annotations: Sequence<KSAnnotation>): String {
            val rendered = annotations.mapNotNull { annotation ->
                val qualifiedName = annotation.annotationType.resolve().declaration.qualifiedName?.asString()
                    ?: return@mapNotNull null
                if (qualifiedName in IGNORED_ANNOTATIONS || qualifiedName.startsWith("kotlin.internal.")) {
                    return@mapNotNull null
                }
                "@$qualifiedName" + renderAnnotationArguments(annotation)
            }.distinct().toList()
            return if (rendered.isEmpty()) "" else rendered.joinToString(" ") + " "
        }

        private fun renderAnnotationArguments(annotation: KSAnnotation): String {
            val explicit = annotation.arguments.filter { it.name != null && it.origin != Origin.SYNTHETIC }
            if (explicit.isEmpty()) return ""
            val parts = mutableListOf<String>()
            for (argument in explicit) {
                val value = renderAnnotationValue(argument.value)
                if (value == null) {
                    report(
                        annotation,
                        "Unsupported argument ${argument.name?.asString()} of annotation " +
                                "${annotation.shortName.asString()}.",
                    )
                    return ""
                }
                parts += "${argument.name!!.asString()} = $value"
            }
            return parts.joinToString(", ", "(", ")")
        }

        private fun renderAnnotationValue(value: Any?): String? = when (value) {
            null -> "null"
            is String -> "\"${escapeStringLiteral(value)}\""
            is Char -> "'${escapeCharLiteral(value)}'"
            is Boolean -> value.toString()
            is Int -> value.toString()
            is Long -> "${value}L"
            is Short -> "$value.toShort()"
            is Byte -> "$value.toByte()"
            is Float -> "${formatFloatingPoint(value.toDouble())}f"
            is Double -> formatFloatingPoint(value)
            is KSType -> value.declaration.qualifiedName?.asString()?.let { "$it::class" }
            is KSClassDeclaration -> value.qualifiedName?.asString()
            is KSName -> value.asString()
            is List<*> -> value.joinToString(", ", "[", "]") { renderAnnotationValue(it) ?: "null" }
            else -> null
        }

        private fun symbolDescription(symbol: KSNode): String = when (symbol) {
            is KSPropertyDeclaration -> "property ${symbol.simpleName.asString()}"
            is KSFunctionDeclaration -> "function ${symbol.simpleName.asString()}"
            else -> symbol.toString()
        }

        /**
         * Returns the validator invocation prefix together with whether the
         * validator accepts `null`, or `null` when no validator is configured
         * or a diagnostic was reported.
         */
        fun validator(
            property: KSPropertyDeclaration,
            propertyName: String,
            validatorType: KSType?,
            valueType: KSType,
        ): ValidatorInfo? {
            if (validatorType == null || validatorType.isUnit()) return null
            if (validatorType.isError) {
                reportUnresolved(property, "The validator of property $propertyName is not resolvable yet.")
                return null
            }
            val declaration = validatorType.declaration as? KSClassDeclaration ?: run {
                report(property, "The validator of property $propertyName must be a class or object.")
                return null
            }
            val dslValidatorArguments = findSuperTypeArguments(declaration, property, DSL_VALIDATOR_NAME)
            if (dslValidatorArguments == null) {
                report(property, "The validator of property $propertyName must implement DslValidator.")
                return null
            }
            val validatedType = dslValidatorArguments.singleOrNull()
            if (validatedType == null || !validatedType.isAssignableFrom(valueType)) {
                report(
                    property,
                    "The validator of property $propertyName validates a type that does not accept ${
                        renderType(
                            property,
                            valueType
                        ) ?: "the property"
                    } values."
                )
                return null
            }
            val prefix = instantiationPrefix(property, propertyName, declaration, "validator") ?: return null
            return ValidatorInfo(prefix, validatedType.isMarkedNullable)
        }

        /**
         * Returns the mapper info, `null` when no mapper is configured or a
         * diagnostic was reported; callers distinguish the two cases through
         * [Checker.valid].
         */
        fun mapper(
            property: KSPropertyDeclaration,
            propertyName: String,
            mapperType: KSType?,
            propertyType: KSType,
        ): MapperInfo? {
            if (mapperType == null || mapperType.isUnit()) return null
            if (mapperType.isError) {
                reportUnresolved(property, "The mapper of property $propertyName is not resolvable yet.")
                return null
            }
            val declaration = mapperType.declaration as? KSClassDeclaration ?: run {
                report(property, "The mapper of property $propertyName must be a class or object.")
                return null
            }
            val dslMapperArguments = findSuperTypeArguments(declaration, property, DSL_MAPPER_NAME)
            if (dslMapperArguments == null) {
                report(property, "The mapper of property $propertyName must implement DslMapper.")
                return null
            }
            if (dslMapperArguments.size != 2 || dslMapperArguments.any { it == null }) {
                report(
                    property,
                    "The mapper of property $propertyName must implement DslMapper with two type arguments."
                )
                return null
            }
            val storedType = dslMapperArguments[0]!!
            val valueType = dslMapperArguments[1]!!
            if (!valueType.isAssignableFrom(propertyType)) {
                report(
                    property,
                    "The mapper of property $propertyName maps a type that does not accept ${
                        renderType(
                            property,
                            propertyType
                        ) ?: "the property"
                    } values."
                )
                return null
            }
            val prefix = instantiationPrefix(property, propertyName, declaration, "mapper") ?: return null
            val storageTypeName = renderType(property, storedType) ?: return null
            return MapperInfo(prefix, storageTypeName, storedType)
        }

        private fun instantiationPrefix(
            property: KSPropertyDeclaration,
            propertyName: String,
            declaration: KSClassDeclaration,
            role: String,
        ): String? {
            val prefix = declaration.qualifiedName?.asString()
            if (prefix == null) {
                report(property, "The $role of property $propertyName has no qualified name.")
                return null
            }
            return when {
                declaration.isCompanionObject || declaration.classKind == ClassKind.OBJECT -> prefix
                declaration.classKind == ClassKind.CLASS ->
                    if (declaration.primaryConstructor?.parameters?.isEmpty() == true) "$prefix()" else {
                        report(
                            property,
                            "The $role of property $propertyName is a class without a no-argument constructor."
                        )
                        null
                    }

                else -> {
                    report(property, "The $role of property $propertyName must be a class or object.")
                    null
                }
            }
        }

        /**
         * Renders a compile-time constant written in string form as a Kotlin
         * literal expression of the property type.
         */
        fun literal(property: KSPropertyDeclaration, propertyName: String, initial: String, type: KSType): String? {
            fun fail(detail: String): String? {
                report(property, "@DslValue.initial of property $propertyName is \"$initial\", which is $detail.")
                return null
            }
            return when (type.makeNotNullable().declaration.qualifiedName?.asString()) {
                "kotlin.Int" -> initial.toLongOrNull()?.takeIf { it in Int.MIN_VALUE..Int.MAX_VALUE }?.toString()
                    ?: fail("not an Int constant")

                "kotlin.Long" -> initial.toLongOrNull()?.let { "${it}L" } ?: fail("not a Long constant")
                "kotlin.Short" -> initial.toLongOrNull()?.takeIf { it in Short.MIN_VALUE..Short.MAX_VALUE }
                    ?.let { "$it.toShort()" }
                    ?: fail("not a Short constant")

                "kotlin.Byte" -> initial.toLongOrNull()?.takeIf { it in Byte.MIN_VALUE..Byte.MAX_VALUE }
                    ?.let { "$it.toByte()" }
                    ?: fail("not a Byte constant")

                "kotlin.Double" -> initial.toDoubleOrNull()?.let(::formatFloatingPoint) ?: fail("not a Double constant")
                "kotlin.Float" -> initial.toFloatOrNull()?.let { "${formatFloatingPoint(it.toDouble())}f" }
                    ?: fail("not a Float constant")

                "kotlin.Boolean" -> when (initial) {
                    "true", "false" -> initial
                    else -> fail("not a Boolean constant")
                }

                "kotlin.Char" -> if (initial.length == 1) "'${escapeCharLiteral(initial[0])}'" else fail("not a single character")
                "kotlin.String" -> "\"${escapeStringLiteral(initial)}\""
                "kotlin.UInt" -> initial.toLongOrNull()?.takeIf { it in 0..UInt.MAX_VALUE.toLong() }?.let { "${it}u" }
                    ?: fail("not a UInt constant")

                "kotlin.ULong" -> initial.toULongOrNull()?.let { "${it}uL" } ?: fail("not a ULong constant")
                "kotlin.UShort" -> initial.toLongOrNull()?.takeIf { it in 0..UShort.MAX_VALUE.toLong() }
                    ?.let { "$it.toUShort()" }
                    ?: fail("not a UShort constant")

                "kotlin.UByte" -> initial.toLongOrNull()?.takeIf { it in 0..UByte.MAX_VALUE.toLong() }
                    ?.let { "$it.toUByte()" }
                    ?: fail("not a UByte constant")

                else -> {
                    report(
                        property,
                        "@DslValue.initial of property $propertyName supports Byte, Short, Int, Long, UByte, UShort, UInt, ULong, Float, Double, Boolean, Char, and String constants."
                    )
                    null
                }
            }
        }

        private fun formatFloatingPoint(value: Double): String {
            val rendered = value.toString()
            return if (rendered.any { it == '.' || it == 'e' || it == 'E' }) rendered else "$rendered.0"
        }

        private fun KSType.isUnit(): Boolean =
            declaration.qualifiedName?.asString() == "kotlin.Unit"

        /**
         * Searches the supertype hierarchy of [declaration] for [qualifiedName]
         * and returns the type arguments of the match as seen from the
         * perspective of [declaration], substituting the type parameters of any
         * generic bases along the way. Returns `null` when the supertype is not
         * implemented or an unresolvable type was met.
         */
        fun findSuperTypeArguments(
            declaration: KSClassDeclaration,
            symbol: KSNode,
            qualifiedName: String,
        ): List<KSType?>? {
            val pending = ArrayDeque<Pair<KSClassDeclaration, Map<KSTypeParameter, KSType>>>()
            pending += declaration to emptyMap()
            val visited = mutableSetOf<String>()
            while (pending.isNotEmpty()) {
                val (current, environment) = pending.removeFirst()
                val currentName = current.qualifiedName?.asString() ?: continue
                if (!visited.add(currentName)) continue
                for (superType in current.superTypes) {
                    val resolved = superType.resolve()
                    if (resolved.isError) {
                        reportUnresolved(symbol, "A supertype of ${symbolDescription(symbol)} is not resolvable yet.")
                        return null
                    }
                    val superDeclaration = resolved.declaration as? KSClassDeclaration ?: continue
                    if (superDeclaration.qualifiedName?.asString() == qualifiedName) {
                        return resolved.arguments.map { argument ->
                            argument.type?.resolve()?.let { resolveThrough(it, environment) }
                        }
                    }
                    val parameters = superDeclaration.typeParameters
                    val nextEnvironment = parameters.zip(resolved.arguments)
                        .mapNotNull { (parameter, argument) ->
                            val argumentType = argument.type?.resolve() ?: return@mapNotNull null
                            parameter to resolveThrough(argumentType, environment)
                        }
                        .toMap()
                    pending += superDeclaration to nextEnvironment
                }
            }
            return null
        }

        private fun resolveThrough(type: KSType, environment: Map<KSTypeParameter, KSType>): KSType =
            (type.declaration as? KSTypeParameter)?.let(environment::get) ?: type
    }

    private class ValidatorInfo(
        val prefix: String,
        val acceptsNull: Boolean,
    )

    private data class MapperInfo(
        val prefix: String,
        val storageTypeName: String,
        val storedType: KSType,
    )

    private class RequiredProperty(
        val name: String,
        val typeName: String,
        val validator: String?,
        val message: String,
    )

    private class Parameter(
        val name: String,
        val typeName: String,
    )

    private class ValueProperty(
        val name: String,
        val typeName: String,
        val storageTypeName: String,
        val initialExpression: String,
        val mapper: String?,
        val validator: String?,
        val validatorAcceptsNull: Boolean,
        val message: String,
    ) {
        fun getterExpression(field: String): String =
            if (mapper == null) field else "$mapper.toValue($field)"
    }

    private class ListProperty(
        val name: String,
        val elementTypeName: String,
        val validator: String?,
        val message: String,
        val children: List<ChildSpec>,
    )

    /**
     * A DslBuilder interface used as a child: its generated builder, result
     * class, and required properties are resolved by name so that the parent
     * generated code can construct and build it.
     */
    private class ChildSpec(
        val functionName: String,
        val builderQualifiedName: String,
        val resultQualifiedName: String,
        val specQualifiedName: String,
        val required: List<RequiredProperty>,
    )

    private class ChildScope(
        val name: String,
        val parameters: List<Parameter>,
        val child: ChildSpec,
    )

    private fun decapitalize(name: String): String =
        if (name.length >= 2 && name[1].isUpperCase()) name else name.replaceFirstChar { it.lowercase() }

    /**
     * The names of the generated classes and function for one DslBuilder
     * interface, derived from the interface name and overridden by the
     * [DslBuilder][top.ltfan.dslutilities.DslBuilder] annotation arguments.
     */
    private class Names(
        val resultName: String,
        val builderName: String,
        val functionName: String,
        val generateFunction: Boolean,
    ) {
        companion object {
            fun of(specName: String, annotation: KSAnnotation?): Names {
                val defaultResult = if (specName.endsWith("Dsl")) {
                    specName.removeSuffix("Dsl").takeIf { it.isNotEmpty() } ?: "${specName}Result"
                } else {
                    "${specName}Result"
                }
                val defaultBuilder = "${specName}Builder"
                val defaultFunction = "build${specName.removeSuffix("Dsl").takeIf { it.isNotEmpty() } ?: specName}"
                val resultName = annotation?.string("resultName").takeUnless { it.isNullOrEmpty() } ?: defaultResult
                val builderName = annotation?.string("builderName").takeUnless { it.isNullOrEmpty() } ?: defaultBuilder
                val generateFunction = annotation?.boolean("generateFunction") ?: true
                val functionName = annotation?.string("functionName").takeUnless { it.isNullOrEmpty() }
                    ?: defaultFunction.takeIf { generateFunction }.orEmpty()
                return Names(resultName, builderName, functionName, generateFunction)
            }
        }
    }

    private companion object {
        const val DSL_BUILDER_ANNOTATION = "top.ltfan.dslutilities.DslBuilder"
        const val DSL_VALUE_ANNOTATION = "top.ltfan.dslutilities.DslValue"
        const val DSL_LIST_ANNOTATION = "top.ltfan.dslutilities.DslList"
        const val DSL_CHILD_ANNOTATION = "top.ltfan.dslutilities.DslChild"
        const val DSL_VALIDATOR_NAME = "top.ltfan.dslutilities.DslValidator"
        const val DSL_MAPPER_NAME = "top.ltfan.dslutilities.DslMapper"
    }
}

private fun KSAnnotated.annotation(qualifiedName: String): KSAnnotation? =
    annotations.firstOrNull {
        it.annotationType.resolve().declaration.qualifiedName?.asString() == qualifiedName
    }

private fun KSAnnotation.string(name: String): String? =
    arguments.firstOrNull { it.name?.asString() == name }?.value as? String

private fun KSAnnotation.boolean(name: String): Boolean? =
    arguments.firstOrNull { it.name?.asString() == name }?.value as? Boolean

private fun KSAnnotation.type(name: String): KSType? =
    when (val value = arguments.firstOrNull { it.name?.asString() == name }?.value) {
        is KSType -> value
        is KSClassDeclaration -> value.asType(emptyList())
        else -> null
    }

private fun KSAnnotation.typeArray(name: String): List<KSType> =
    (arguments.firstOrNull { it.name?.asString() == name }?.value as? List<*>)
        ?.mapNotNull { element ->
            when (element) {
                is KSType -> element
                is KSClassDeclaration -> element.asType(emptyList())
                else -> null
            }
        }
        .orEmpty()

private fun escapeStringLiteral(value: String): String = buildString {
    for (character in value) {
        when (character) {
            '\\' -> append("\\\\")
            '"' -> append("\\\"")
            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            '$' -> append("\\$")
            else -> append(character)
        }
    }
}

private fun escapeCharLiteral(character: Char): String = when (character) {
    '\\' -> "\\\\"
    '\'' -> "\\'"
    '\n' -> "\\n"
    '\r' -> "\\r"
    '\t' -> "\\t"
    '$' -> "\\$"
    else -> character.toString()
}

private const val EXTENSION_FUNCTION_TYPE = "ExtensionFunctionType"
private const val PARAMETER_NAME = "ParameterName"
private const val UNIT_TYPE = "kotlin.Unit"

/**
 * Type annotations that are compiler markers rather than user-visible
 * annotations; they are expressed through the rendered syntax instead of
 * being copied.
 */
private val IGNORED_ANNOTATIONS = setOf(
    "kotlin.ExtensionFunctionType",
    "kotlin.ParameterName",
    "kotlin.UnsafeVariance",
)

/** Provides [DslProcessor] to the KSP runtime through the service loader. */
class DslProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): DslProcessor =
        DslProcessor(environment.codeGenerator, environment.logger)
}
