package top.ltfan.dslutilities

/**
 * Validates values of a DSL property. Implementations are referenced
 * from [DslValue] and [DslList] annotations and are invoked by the code
 * generated by the dsl-utilities-ksp processor.
 *
 * @param T The type of the validated values.
 */
public fun interface DslValidator<in T> {
    /** Returns whether [value] is accepted for the validated property. */
    public fun validate(value: T): Boolean
}

/**
 * Maps values of a DSL property between the declared type [O] and the
 * stored representation [I]. Implementations are referenced from the
 * [DslValue.mapper] annotation argument and are invoked by the code
 * generated by the dsl-utilities-ksp processor.
 *
 * @param I The stored representation of the value.
 * @param O The declared type of the DSL property.
 */
public interface DslMapper<I, O> {
    /** Maps the declared [value] to its stored representation. */
    public fun toStored(value: O): I

    /** Maps the [stored] representation back to the declared type. */
    public fun toValue(stored: I): O
}
