package top.ltfan.dslutilities

/**
 * Validates values of a DSL property. Implementations are referenced
 * from [DslValue] and [DslList] annotations and are invoked by the code
 * generated by the dsl-utilities-ksp processor.
 *
 * @param T The type of the validated values.
 */
public fun interface DslValidator<in T> {
    /** Returns whether [value] is accepted for the validated property. */
    public fun validate(value: T): Boolean
}
